In [34]:
import pandas as pd

In [35]:
dates={
    'name':['a','b','c','d','e','f','g','h','i','j'],
    'date':['17-01-2004','abcd','03/05/12','12-13-2004','01-08-05','2004-11-31','','2006-02-29','15/07/2003','']
}

In [36]:
df=pd.DataFrame(dates)

In [37]:
df

  name        date
0    a  17-01-2004
1    b        abcd
2    c    03/05/12
3    d  12-13-2004
4    e    01-08-05
5    f  2004-11-31
6    g
7    h  2006-02-29
8    i  15/07/2003
9    j

In [38]:
df['date']=pd.to_datetime(df['date'],format='mixed',errors='coerce')

In [39]:
df

  name       date
0    a 2004-01-17
1    b        NaT
2    c 2012-03-05
3    d 2004-12-13
4    e 2005-01-08
5    f        NaT
6    g        NaT
7    h        NaT
8    i 2003-07-15
9    j        NaT

In [40]:
df[df['date'].isna()]

  name date
1    b  NaT
5    f  NaT
6    g  NaT
7    h  NaT
9    j  NaT

In [41]:
df.dropna(subset='date',inplace=True)

In [50]:
df=df.reset_index()

In [52]:
df.drop(columns=['index'],inplace=True)

In [53]:
df

  name       date
0    a 2004-01-17
1    c 2012-03-05
2    d 2004-12-13
3    e 2005-01-08
4    i 2003-07-15